fix: get metadata name from service file

diff --git a/.bluemix/pipeline.yml b/.bluemix/pipeline.yml
--- a/.bluemix/pipeline.yml
+++ b/.bluemix/pipeline.yml
@@ -46,7 +46,7 @@ stages:
       echo "Build environment variables:"
       echo "REGISTRY_URL=${REGISTRY_URL}"
       echo "REGISTRY_NAMESPACE=${REGISTRY_NAMESPACE}"
-      echo "IMAGE_NAME=${IMAGE_NAME}"
+      echo "IMAGE_NAME=${IMAGE_NAME}" 
       echo "BUILD_NUMBER=${BUILD_NUMBER}"
       echo "ARCHIVE_DIR=${ARCHIVE_DIR}"
       echo "APP_PORT=${APP_PORT}"
@@ -155,7 +155,7 @@ stages:
       #!/bin/bash
       export PATH="downloads:$PATH"
 
-      #View build properties
+      # View build properties
       cat build.properties
 
       echo "Check cluster availability"
@@ -174,7 +174,7 @@ stages:
       fi
 
       KNATIVE_RUNNING=$(kubectl get pods --namespace knative-serving -o json | jq '.items|length')
-      if [ "0" == $KNATIVE_RUNNING ]; then
+      if [ "0" == "$KNATIVE_RUNNING" ]; then
           echo "Knative is required but is not running in this cluster. Ensure that the cluster's workers meet the minimum requirements for Istio. Install the Knative add-on and retry. Note that the Knative add-on is not supported on lite clusters."
           exit 1
       fi
@@ -195,30 +195,34 @@ stages:
         echo -e "Cluster role binding created."
       fi
 
-      #Update service.yaml with service and image name
+      # Update service.yaml with service and image name
       echo "=========================================================="
       echo "CHECKING SERVICE.YAML manifest"
       if [ ! -f ${SERVICE_FILE} ]; then
         echo -e "Knative service file '${SERVICE_FILE}' not found. Ensure a Knative service definition file named '${SERVICE_FILE}' is located at the project's root directory. Alternatively, change the SERVICE_FILE environment property in the Deploy stage configuration."
         exit 1
-      else
-        echo "UPDATING service manifest with image information"
-        echo "${SERVICE_FILE_UPDATE_INSTRUCTIONS}" | sed -e "s/REGISTRY_URL/${REGISTRY_URL}/g" -e "s/REGISTRY_NAMESPACE/${REGISTRY_NAMESPACE}/g" -e "s/IMAGE_NAME/${IMAGE_NAME}/g" -e "s/BUILD_NUMBER/${BUILD_NUMBER}/g" > ${SERVICE_FILE_UPDATE_INSTRUCTIONS_FILE}
-        echo "Service file update instructions:"
-        cat ${SERVICE_FILE_UPDATE_INSTRUCTIONS_FILE}
-        IMAGE_REPOSITORY=${REGISTRY_URL}/${REGISTRY_NAMESPACE}/${IMAGE_NAME}
-        echo -e "Updating ${SERVICE_FILE} with image name: ${IMAGE_REPOSITORY}"
-        NEW_SERVICE_FILE=tmp.${SERVICE_FILE}
-        yq write --doc 0 -s ${SERVICE_FILE_UPDATE_INSTRUCTIONS_FILE} ${SERVICE_FILE} > ${NEW_SERVICE_FILE}
-        SERVICE_FILE=${NEW_SERVICE_FILE} # use modified file
+      fi
+      # Get kube service name from metadata name in service file
+      export KUBE_SERVICE_NAME=$(yq read $SERVICE_FILE metadata.name)
+      if [ "$KUBE_SERVICE_NAME" == "null" ]; then
+          echo "ERROR: no service name found in service file, $SERVICE_FILE"
+          exit 1
       fi
 
+      echo "UPDATING service manifest with image information"
+      echo "${SERVICE_FILE_UPDATE_INSTRUCTIONS}" | sed -e "s/REGISTRY_URL/${REGISTRY_URL}/g" -e "s/REGISTRY_NAMESPACE/${REGISTRY_NAMESPACE}/g" -e "s/IMAGE_NAME/${IMAGE_NAME}/g" -e "s/BUILD_NUMBER/${BUILD_NUMBER}/g" > ${SERVICE_FILE_UPDATE_INSTRUCTIONS_FILE}
+      echo "Service file update instructions:"
+      cat ${SERVICE_FILE_UPDATE_INSTRUCTIONS_FILE}
+      IMAGE_REPOSITORY=${REGISTRY_URL}/${REGISTRY_NAMESPACE}/${IMAGE_NAME}
+      echo -e "Updating ${SERVICE_FILE} with image name: ${IMAGE_REPOSITORY}"
+      UPDATED_SERVICE_FILE=tmp.${SERVICE_FILE}
+      yq write --doc 0 -s ${SERVICE_FILE_UPDATE_INSTRUCTIONS_FILE} ${SERVICE_FILE} > ${UPDATED_SERVICE_FILE}
 
-      # Deploy the most recent revision of the specified image
+      # Deploy the most recent revision of the specified image as specified in the updated service file
       echo "=========================================================="
-      cat ${SERVICE_FILE}
+      cat ${UPDATED_SERVICE_FILE}
       echo "Deploying Knative service..."
-      kubectl apply -f ${SERVICE_FILE}
+      kubectl apply -f ${UPDATED_SERVICE_FILE}
 
 
       echo "Checking if application is ready..."
@@ -226,14 +230,14 @@ stages:
       do
         sleep 3
 
-        kubectl get ksvc/${IMAGE_NAME} --output=custom-columns=DOMAIN:.status.conditions[*].status
-        SVC_STATUS_READY=$( kubectl get ksvc/${IMAGE_NAME} -o json | jq '.status?.conditions[]?.status?|select(. == "True")' )
+        kubectl get ksvc/${KUBE_SERVICE_NAME} --output=custom-columns=DOMAIN:.status.conditions[*].status
+        SVC_STATUS_READY=$( kubectl get ksvc/${KUBE_SERVICE_NAME} -o json | jq '.status?.conditions[]?.status?|select(. == "True")' )
         echo SVC_STATUS_READY=$SVC_STATUS_READY
 
-        SVC_STATUS_NOT_READY=$( kubectl get ksvc/${IMAGE_NAME} -o json | jq '.status?.conditions[]?.status?|select(. == "False")' )
+        SVC_STATUS_NOT_READY=$( kubectl get ksvc/${KUBE_SERVICE_NAME} -o json | jq '.status?.conditions[]?.status?|select(. == "False")' )
         echo SVC_STATUS_NOT_READY=$SVC_STATUS_NOT_READY
 
-        SVC_STATUS_UNKNOWN=$( kubectl get ksvc/${IMAGE_NAME} -o json | jq '.status?.conditions[]?.status?|select(. == "Unknown")' )
+        SVC_STATUS_UNKNOWN=$( kubectl get ksvc/${KUBE_SERVICE_NAME} -o json | jq '.status?.conditions[]?.status?|select(. == "Unknown")' )
         echo SVC_STATUS_UNKNOWN=$SVC_STATUS_UNKNOWN
 
         if [ \( -n "$SVC_STATUS_NOT_READY" \) -o \( -n "$SVC_STATUS_UNKNOWN" \) ]; then
@@ -246,14 +250,14 @@ stages:
         fi
       done
       echo "Application service details:"
-      kubectl describe ksvc/${IMAGE_NAME}
+      kubectl describe ksvc/${KUBE_SERVICE_NAME}
       if [ \( -n "$SVC_STATUS_NOT_READY" \) -o \( -n "$SVC_STATUS_UNKNOWN" \) ]; then
         echo "Application is not ready after waiting maximum time"
         exit 1
       fi
 
       # Determine app url for polling from knative service
-      TEMP_URL=$( kubectl get ksvc/${IMAGE_NAME} -o json | jq '.status.url' )
+      TEMP_URL=$( kubectl get ksvc/${KUBE_SERVICE_NAME} -o json | jq '.status.url' )
       echo "Application status URL: $TEMP_URL"
       TEMP_URL=${TEMP_URL%\"} # remove end quote
       TEMP_URL=${TEMP_URL#\"} # remove beginning quote
@@ -277,8 +281,10 @@ stages:
       kubernetes_cluster: ${PROD_CLUSTER_NAME}
     script: |-
       export PATH="downloads:$PATH"
-      kubectl get ksvc/${IMAGE_NAME} -o json | jq '.status.url'
-      TEMP_URL=$( kubectl get ksvc/${IMAGE_NAME} -o json | jq '.status.url' )
+      export KUBE_SERVICE_NAME=$(yq read $SERVICE_FILE metadata.name)
+
+      kubectl get ksvc/${KUBE_SERVICE_NAME} -o json | jq '.status.url'
+      TEMP_URL=$( kubectl get ksvc/${KUBE_SERVICE_NAME} -o json | jq '.status.url' )
       TEMP_URL=${TEMP_URL%\"} # remove end quote
       TEMP_URL=${TEMP_URL#\"} # remove beginning quote
       export APPLICATION_URL=$TEMP_URL
